[deps]
ADNLPModels = "54578032-b7ea-4c30-94aa-7cbd1cce6c9a"
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
MLDatasets = "eb30cadb-4394-5ae3-aed4-317e484a6458"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
NLPModelsModifiers = "e01155f1-5c6f-4375-a9d8-616dd036575f"
PGFPlots = "3b7a836e-365b-5785-a47d-02c71176b4aa"
PGFPlotsX = "8314cec4-20b6-5062-9cdb-752b83310925"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProximalOperators = "a725b495-10eb-56fe-b38b-717eba820537"
RegularizedOptimization = "196f2941-2d58-45ba-9f13-43a2532b2fa8"
RegularizedProblems = "ea076b23-609f-44d2-bb12-a4ae45328278"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
ShiftedProximalOperators = "d4fd37fa-580c-4e43-9b30-361c21aae263"
SolverBenchmark = "581a75fa-a23a-52d0-a590-d6201de2218a"
Wavelets = "29a6e085-ba6d-5f35-a997-948ac2efa89a"

[compat]
ADNLPModels = "0.7"
DifferentialEquations = "7"
NLPModels = "0.19, 0.20, 0.21"
NLPModelsModifiers = "0.7"
PGFPlots = "^3.4"
ProximalOperators = "0.15"
RegularizedProblems = "0.1"
